<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>a455657e-58b4-4571-8e2a-b09bcdd5817f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c3d9929-956c-4115-bcf7-f3abd7323085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>373802b9-648c-4823-be73-d4dec7ffa0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6943d4df-306f-4f93-a022-167133097ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>5c0651f2-a7bd-4863-9932-df072665338e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/section[1]/div[@class=&quot;container-fluid section-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-18 col-sm-18 col-md-18 col-lg-18 col-vl-18&quot;]/div[@id=&quot;ng-view&quot;]/div[@id=&quot;ng-view&quot;]/div[@class=&quot;col-sm-18&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-18&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-18&quot;]/div[@class=&quot;panel&quot;]/form[@class=&quot;form-inline ng-valid ng-dirty ng-valid-parse ng-submitted&quot;]/div[@class=&quot;panel-body&quot;]/button[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>d52cb106-6b0c-4400-903d-28dcb61e3747</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>de7c439c-06a1-4528-935e-0b070611b918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ng-view']/div/div/div/div/div[2]/div/form/div/button</value>
      <webElementGuid>96d33794-0827-49af-9ff2-4ddbd1374f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Facilities'])[1]/following::button[1]</value>
      <webElementGuid>15aac129-7e99-46ed-a08e-725cc502be50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facilities'])[2]/following::button[1]</value>
      <webElementGuid>aba7145b-867d-4e2d-a2bc-c078b9ac4f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facility:'])[1]/preceding::button[1]</value>
      <webElementGuid>6cdc99aa-0b06-44fa-ab08-caefffe2f37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hybrent'])[1]/preceding::button[1]</value>
      <webElementGuid>6507b6d5-5204-44e3-adf6-d6d8269c931b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>4e04b833-771e-419b-a970-4830d4a9f937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>e8b61b71-fc65-4525-8b6a-0b26aab2dc1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>d806e1eb-c25f-4800-b23f-98b42b93cc5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
