<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>07565ebf-f275-4f4a-9b2d-aefea3752f8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.pull-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>581ce054-aaa2-4956-8644-a6ceeb14b246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right</value>
      <webElementGuid>18aefb4a-71b9-4524-9f7d-8efe378989d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>108a3dba-2ed7-4f55-ba87-d6404785c393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>createDepartment()</value>
      <webElementGuid>bed83bf9-ea97-4c4a-aba5-6620ed9afe5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>81ae8a23-b814-4494-a159-d437e8d18182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/section[1]/div[@class=&quot;container-fluid section-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-18 col-sm-18 col-md-18 col-lg-18 col-vl-18&quot;]/div[@id=&quot;ng-view&quot;]/div[@id=&quot;ng-view&quot;]/div[@class=&quot;col-sm-18&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-18&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-18&quot;]/div[@class=&quot;pagehead&quot;]/button[@class=&quot;btn btn-primary pull-right&quot;]</value>
      <webElementGuid>680d1264-7166-49c6-8d38-da5de9b711c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>f3b449ad-0e1e-4eb8-ab16-ef11b09f48a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ng-view']/div/div/div/div/div/div/button</value>
      <webElementGuid>042767ba-52fa-4314-88fa-0dfad5404097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Categories'])[1]/following::button[1]</value>
      <webElementGuid>43864105-220a-4374-9769-7966f4f89485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search by'])[1]/preceding::button[1]</value>
      <webElementGuid>050a4fef-0d8f-4461-b8b6-b1c02548c5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facilities'])[2]/preceding::button[1]</value>
      <webElementGuid>32fe6388-05b3-4dde-b724-ce886f2462ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>0c8292fa-25b3-4592-94c3-460d5d463a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/button</value>
      <webElementGuid>ab6c4527-8ff4-4515-a0b4-5f671ac5b55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>e42adc1d-975e-4abc-8f8c-13cbab21678e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
