<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>85049bc6-5d41-49f9-8a74-48b8503347fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-lg.btn-primary.hyb-login-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d4cbdfb-647c-4500-96d4-b5a6e173487e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4dfed126-ec92-4393-aede-1cac582441f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary hyb-login-btn</value>
      <webElementGuid>aafb6fea-f148-4326-aabf-5824c6593cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Login
                            </value>
      <webElementGuid>6638aa91-3498-425a-9512-54b47891d135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/section[1]/div[@class=&quot;container-fluid section-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-18 col-sm-18 col-md-18 col-lg-18 col-vl-18&quot;]/div[@id=&quot;ng-view&quot;]/div[@id=&quot;ng-view&quot;]/div[@class=&quot;container-fluid margin-r-283&quot;]/div[@class=&quot;row&quot;]/div[2]/div[@class=&quot;site-well site-well-white col-centered&quot;]/div[1]/form[@class=&quot;ng-valid ng-dirty ng-valid-parse&quot;]/div[@class=&quot;controls&quot;]/button[@class=&quot;btn btn-lg btn-primary hyb-login-btn&quot;]</value>
      <webElementGuid>1a39fdae-dbcb-4440-be89-1f9237e031a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d32fb587-70ea-4da7-ac3e-00ffd96f2eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>eb29f0fb-da99-40a5-a546-66e221177963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary hyb-login-btn</value>
      <webElementGuid>3b2de5a8-6090-4853-8a4e-e01290bb9b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Login
                            </value>
      <webElementGuid>5d8ef17f-eef3-4dfd-a6d4-f459983dfec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/section[1]/div[@class=&quot;container-fluid section-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-18 col-sm-18 col-md-18 col-lg-18 col-vl-18&quot;]/div[@id=&quot;ng-view&quot;]/div[@id=&quot;ng-view&quot;]/div[@class=&quot;container-fluid margin-r-283&quot;]/div[@class=&quot;row&quot;]/div[2]/div[@class=&quot;site-well site-well-white col-centered&quot;]/div[1]/form[@class=&quot;ng-valid ng-dirty ng-valid-parse&quot;]/div[@class=&quot;controls&quot;]/button[@class=&quot;btn btn-lg btn-primary hyb-login-btn&quot;]</value>
      <webElementGuid>18611be3-242e-40ab-a553-d6c4c1c0432e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>8db84374-2641-4324-9926-6d4c2f979623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ng-view']/div/div/div[2]/div/div/form/div[3]/button</value>
      <webElementGuid>add5e442-915d-40ff-b446-d1d02233c7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password:'])[1]/following::button[1]</value>
      <webElementGuid>e2eb41fc-cf41-4604-a79c-afefa82a59f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password'])[1]/preceding::button[1]</value>
      <webElementGuid>a8b8d0ef-3cff-409e-a6ce-5b91fc6be814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>134b181c-e2ed-49c7-af55-e797c7c32ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                                Login
                            ' or . = '
                                Login
                            ')]</value>
      <webElementGuid>23bf9056-0413-4a73-ab5a-b7bc3a4850d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
